dpp.version=${project.version}

server.port=${PORT:8080}

spring.profiles.active=@mavenProfile@

dpp.secret.key=dpp_secret_key_for_encrypt_and_decrypt
zendesk.api.url=https://yoursubdomain.zendesk.com
proxy.public.url=

zendesk.oauth.client.id=dpp-oauth-client-id
zendesk.oauth.scope=read tickets:write
# max expires_in=48 hours
zendesk.oauth.token.expires=172800
# max refresh_token_expires_in=90 days
zendesk.oauth.refreshToken.expires=7776000

logging.level.root=INFO
logging.threshold.console=TRACE
logging.pattern.console=%-5level - %msg%n

logging.level.com.roundrobin_assignment.dpp=DEBUG
#logging.level.com.roundrobin_assignment.dpp=INFO
#logging.level.com.roundrobin_assignment.dpp=WARN