#all properties https://www.javatpoint.com/spring-boot-properties

server.port=${PORT:8080}

logging.level.root=INFO
logging.threshold.console=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

spring.profiles.active=@mavenProfile@

spring.jmx.enabled=false
